exports.cookieList = [
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "_l_g_",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "Ug%3D%3D",
    "id": 1
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "_nk_",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "tb6248905145",
    "id": 2
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "_tb_token_",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "eb7b96677a353",
    "id": 3
  },
  {
    "domain": ".tmall.com",
    "expirationDate": 2242007046,
    "hostOnly": false,
    "httpOnly": false,
    "name": "cna",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "qSCMGG32YFQCATr3gaLS7G4v",
    "id": 4
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": true,
    "name": "cookie1",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "VAiXVw%2BfuIhhIDzcGT1EhcI4LBTOVixtIcpjrGzHgZI%3D",
    "id": 5
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": true,
    "name": "cookie17",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "UUpgRsBaQjPNLMe9jg%3D%3D",
    "id": 6
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": true,
    "name": "cookie2",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "1d60079d5730e2f3d7c6b29cfda02491",
    "id": 7
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "csg",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "5162aaa7",
    "id": 8
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "dnk",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "tb6248905145",
    "id": 9
  },
  {
    "domain": ".tmall.com",
    "expirationDate": 1927118346.696241,
    "hostOnly": false,
    "httpOnly": true,
    "name": "enc",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "chqv9QoMFCTRJlciOK2s0gFYZY06nf%2BiO3LKkLSjDe%2FkRXpR27JO%2B4tu%2BAG%2BQ8Sl4PIj1%2B%2FBVgxBQhkDYiwy0VkrbzslPyaCKa8p9BU1H0Y%3D",
    "id": 10
  },
  {
    "domain": ".tmall.com",
    "expirationDate": 1614350346.695012,
    "hostOnly": false,
    "httpOnly": false,
    "name": "hng",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "CN%7Czh-CN%7CCNY%7C156",
    "id": 11
  },
  {
    "domain": ".tmall.com",
    "expirationDate": 1627281546,
    "hostOnly": false,
    "httpOnly": false,
    "name": "isg",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "BGxsvv-FIC7INjQJPJszKvKlPUyeJRDPVuoAYMatepe60Qzb7jEUXXxr9ZHp2Ugn",
    "id": 12
  },
  {
    "domain": ".tmall.com",
    "expirationDate": 1627281546,
    "hostOnly": false,
    "httpOnly": false,
    "name": "l",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "eBIcSaXmjgkU2ojzBOfZnurza779IIRAguPzaNbMiOCPOU5e59EdW6MjIj8wCnGNhsGeR3usQ4cJBeYBcCY6LRYCnrZgU8Hmn",
    "id": 13
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "lgc",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "tb6248905145",
    "id": 14
  },
  {
    "domain": ".tmall.com",
    "expirationDate": 1643294346.696,
    "hostOnly": false,
    "httpOnly": false,
    "name": "lid",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "tb6248905145",
    "id": 15
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "login",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "true",
    "id": 16
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "sg",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "593",
    "id": 17
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": true,
    "name": "sgcookie",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "E100JJ053Ydz7EPTTj3Mt%2FCoXZNT4KPe3M2dpLiUmPBBF3W7LMHveLy0PoMJax7WGdUf%2B7YGAdGK5WwlzwVBwXCPMQ%3D%3D",
    "id": 18
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "t",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "38dbfaad74bd148a80b6ae8761f06b38",
    "id": 19
  },
  {
    "domain": ".tmall.com",
    "expirationDate": 1627281546,
    "hostOnly": false,
    "httpOnly": false,
    "name": "tfstk",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "chdOBP1Lj2U9rg_pzdH3c9kcbvROZykd0RsuM4fEfZ4td1PAiiAkwZl-5aZO92C..",
    "id": 20
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "tracknick",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "tb6248905145",
    "id": 21
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "uc1",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "cookie16=UtASsssmPlP%2Ff1IHDsDaPRu%2BPw%3D%3D&existShop=false&cookie14=Uoe1g86oxeMvww%3D%3D&cookie15=WqG3DMC9VAQiUQ%3D%3D&cookie21=U%2BGCWk%2F7oPIg&pas=0",
    "id": 22
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": true,
    "name": "uc3",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "nk2=F5RDLjnzk5X7lM0R&lg2=WqG3DMC9VAQiUQ%3D%3D&id2=UUpgRsBaQjPNLMe9jg%3D%3D&vt3=F8dCuAb1Hf2tVhze8d8%3D",
    "id": 23
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": true,
    "name": "uc4",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "nk4=0%40FY4I7WeZhDNbV8nALXRBcHrTa2hZBBY%3D&id4=0%40U2gqyZAnTKyW1%2Bb2bwFpeUXXRkLzLYvD",
    "id": 24
  },
  {
    "domain": ".tmall.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "unb",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "2210460696809",
    "id": 25
  },
  {
    "domain": ".tmall.com",
    "expirationDate": 1611763595,
    "hostOnly": false,
    "httpOnly": false,
    "name": "xlly_s",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "1",
    "id": 26
  },
  {
    "domain": "www.tmall.com",
    "expirationDate": 1643265550,
    "hostOnly": true,
    "httpOnly": false,
    "name": "cq",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "ccp%3D0",
    "id": 27
  }
]
